apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scaler
  namespace: sparrowdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scaler
  template:
    metadata:
      labels:
        app: custom-scaler
    spec:
      containers:
        - name: custom-scaler
          image: bnainar/custom-scaler:latest
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "300Mi"
          livenessProbe:
            httpGet:
              path: /status
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
          - name: config-volume
            mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: custom-scaler-config
          items:
          - key: config
            path: staging.json
  strategy:
    type: RollingUpdate
