apiVersion: v1
kind: Service
metadata:
  name: custom-scaler-svc
  namespace: sparrowdesk
spec:
  selector:
    app: custom-scaler
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
