apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sparrowdesk
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
