---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-hpa
  namespace: sparrowdesk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 10
    scaleDown:
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 1